# Generated by Django 4.0.6 on 2022-07-06 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.TimeField(),
        ),
    ]
