# Generated by Django 4.0.6 on 2022-07-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_schedule_date_alter_schedule_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
